spring:
  jpa:
    show-sql: true
    properties:
      hibernate.dialect: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      use-new-id-generator-mappings: false
  h2:
    console:
      enabled: true
  profiles:
    include: oauth,real-db
  redis:
    host: localhost
    port: 6379
    session:
      timeout: 600
      store-type: redis
      redis:
        flush-mode: on-save
        namespace: spring:session